/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
    ACol: typeof import('ant-design-vue/es')['Col']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ATag: typeof import('ant-design-vue/es')['Tag']
    Badge: typeof import('./src/components/Badge/Badge.vue')['default']
    Button: typeof import('./src/components/Button/Button.vue')['default']
    ButtonIcon: typeof import('./src/components/Button/ButtonIcon.vue')['default']
    Checkbox: typeof import('./src/components/Table/components/FilterType/Checkbox.vue')['default']
    CheckFilter: typeof import('./src/components/FilterForm/src/components/CheckFilter.vue')['default']
    DateFilter: typeof import('./src/components/FilterForm/src/components/DateFilter.vue')['default']
    Datepicker: typeof import('./src/components/Table/components/FilterType/Datepicker.vue')['default']
    Dropdown: typeof import('./src/components/Dropdown/Dropdown.vue')['default']
    DropdownButton: typeof import('./src/components/Button/DropdownButton.vue')['default']
    DynamicTable: typeof import('./src/components/Table/DynamicTable.vue')['default']
    FileUploader: typeof import('./src/components/FileUploader/FileUploader.vue')['default']
    Filter: typeof import('./src/components/Table/components/Filter.vue')['default']
    FilterForm: typeof import('./src/components/FilterForm/index.vue')['default']
    HelloWorld: typeof import('./src/components/Example/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/Icon/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/Icon/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/Icon/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/Icon/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/Icon/IconTooling.vue')['default']
    Modal: typeof import('./src/components/Modal/Modal.vue')['default']
    Radio: typeof import('./src/components/Table/components/FilterType/Radio.vue')['default']
    RadioSelectFilter: typeof import('./src/components/FilterForm/src/components/RadioSelectFilter.vue')['default']
    RangeDateFilter: typeof import('./src/components/FilterForm/src/components/RangeDateFilter.vue')['default']
    RangeDatePicker: typeof import('./src/components/Table/components/FilterType/RangeDatePicker.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/Table/components/FilterType/Select.vue')['default']
    SelectFilter: typeof import('./src/components/FilterForm/src/components/SelectFilter.vue')['default']
    SvgIcon: typeof import('./src/components/Icon/SvgIcon.vue')['default']
    TableFilter: typeof import('./src/components/Table/components/TableFilter.vue')['default']
    TableSegmentButton: typeof import('./src/components/Table/components/TableSegmentButton.vue')['default']
    TableTags: typeof import('./src/components/Table/components/TableTags.vue')['default']
    TheWelcome: typeof import('./src/components/Example/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/Example/WelcomeItem.vue')['default']
  }
}
