/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABadge: typeof import('ant-design-vue/es')['Badge']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AInput: typeof import('ant-design-vue/es')['Input']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    Badge: typeof import('./src/components/Badge/Badge.vue')['default']
    Button: typeof import('./src/components/Button/Button.vue')['default']
    ButtonIcon: typeof import('./src/components/Button/ButtonIcon.vue')['default']
    Checkbox: typeof import('./src/components/Table/components/FilterType/Checkbox.vue')['default']
    Datepicker: typeof import('./src/components/Table/components/FilterType/Datepicker.vue')['default']
    Dropdown: typeof import('./src/components/Dropdown/Dropdown.vue')['default']
    DropdownButton: typeof import('./src/components/Button/DropdownButton.vue')['default']
    Filter: typeof import('./src/components/Table/components/Filter.vue')['default']
    FilterContainer: typeof import('./src/components/Table/components/FilterContainer.vue')['default']
    FilterLabel: typeof import('./src/components/Table/components/FilterLabel.vue')['default']
    FilterTable: typeof import('./src/components/Table/FilterTable.vue')['default']
    FilterType: typeof import('./src/components/Table/components/FilterType/FilterType.vue')['default']
    FilterTypes: typeof import('./src/components/Table/components/FilterType/FilterTypes.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/Icon/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/Icon/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/Icon/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/Icon/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/Icon/IconTooling.vue')['default']
    Modal: typeof import('./src/components/Modal/Modal.vue')['default']
    Radio: typeof import('./src/components/Table/components/FilterType/Radio.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/Table/components/FilterType/Select.vue')['default']
    SvgIcon: typeof import('./src/components/Icon/SvgIcon.vue')['default']
    Table: typeof import('./src/components/Table/Table.vue')['default']
    TableContainer: typeof import('./src/components/TableContainer/TableContainer.vue')['default']
    TableFilter: typeof import('./src/components/Table/TableFilter.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
