/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

import { useI18n } from 'vue-i18n'

declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    $t: VueI18nTranslation<
      Messages,
      Locales,
      RemoveIndexSignature<{
        [K in keyof DefineLocaleMessage]: DefineLocaleMessage[K]
      }>
    >
  }

  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    ADropdownButton: typeof import('ant-design-vue/es')['DropdownButton']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle']
    Badge: typeof import('./src/components/Badge/Badge.vue')['default']
    BasicButton: typeof import('./src/components/Button/BasicButton.vue')['default']
    Button: typeof import('./src/components/Button/Button.vue')['default']
    ButtonIcon: typeof import('./src/components/Button/ButtonIcon.vue')['default']
    Checkbox: typeof import('./src/components/Table/components/FilterType/Checkbox.vue')['default']
    CheckFilter: typeof import('./src/components/FilterForm/src/components/CheckFilter.vue')['default']
    DateFilter: typeof import('./src/components/FilterForm/src/components/DateFilter.vue')['default']
    Description: typeof import('./src/components/Description/Description.vue')['default']
    Dropdown: typeof import('./src/components/Dropdown/Dropdown.vue')['default']
    DropdownButton: typeof import('./src/components/Button/DropdownButton.vue')['default']
    DynamicTable: typeof import('./src/components/Table/DynamicTable.vue')['default']
    Filter: typeof import('./src/components/Table/components/Filter.vue')['default']
    FilterCheckbox: typeof import('./src/components/Filter/components/FilterCheckbox.vue')['default']
    FilterContainer: typeof import('./src/components/Table/components/FilterContainer.vue')['default']
    FilterDatePicker: typeof import('./src/components/Filter/components/FilterDatepicker.vue')['default']
    FilterForm: typeof import('./src/components/FilterForm/index.vue')['default']
    FilterLabel: typeof import('./src/components/Table/components/FilterLabel.vue')['default']
    FilterRadio: typeof import('./src/components/Filter/components/FilterRadio.vue')['default']
    FilterSelect: typeof import('./src/components/Filter/components/FilterSelect.vue')['default']
    FilterTable: typeof import('./src/components/Table/FilterTable.vue')['default']
    FilterType: typeof import('./src/components/Table/components/FilterType/FilterType.vue')['default']
    FilterTypes: typeof import('./src/components/Table/components/FilterType/FilterTypes.vue')['default']
    HelloWorld: typeof import('./src/components/Example/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/Icon/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/Icon/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/Icon/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/Icon/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/Icon/IconTooling.vue')['default']
    Modal: typeof import('./src/components/Modal/Modal.vue')['default']
    Radio: typeof import('./src/components/Table/components/FilterType/Radio.vue')['default']
    RadioSelectFilter: typeof import('./src/components/FilterForm/src/components/RadioSelectFilter.vue')['default']
    RangeDate: typeof import('./src/components/Table/components/FilterType/RangeDate.vue')['default']
    RangeDateFilter: typeof import('./src/components/FilterForm/src/components/RangeDateFilter.vue')['default']
    RangeDatePicker: typeof import('./src/components/Table/components/FilterType/RangeDatePicker.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/Table/components/FilterType/Select.vue')['default']
    SelectFilter: typeof import('./src/components/FilterForm/src/components/SelectFilter.vue')['default']
    SvgIcon: typeof import('./src/components/Icon/SvgIcon.vue')['default']
    Table: typeof import('./src/components/Table/Table.vue')['default']
    TableContainer: typeof import('./src/components/TableContainer/TableContainer.vue')['default']
    TableFilter: typeof import('./src/components/Table/TableFilter.vue')['default']
    TableSegmentButton: typeof import('./src/components/Table/components/TableSegmentButton.vue')['default']
    TableTags: typeof import('./src/components/Table/components/TableTags.vue')['default']
    TheWelcome: typeof import('./src/components/Example/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/Example/WelcomeItem.vue')['default']
  }
}
